[package]
name = "actor-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
flume = "0.11.1"
futures = "0.3.31"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"
